# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- build

pool: flaskfoolagent
variables:
  azureServiceConnectionId: 'myConnection'
  webAppName: 'udacityFlaskApp001'
  projectRoot: $(System.DefaultWorkingDirectory)

stages:
- stage: build
  displayName: Build stage
  jobs:
    - job: BuildJob
      pool: flaskfoolagent
      steps:
        - script: |
            export PATH=$HOME/.local/bin:$PATH
            python3.10 -m pip install -r requirements.txt
          workingDirectory: $(projectRoot)
          displayName: 'Step - Install requirements.txt'

        - task: ArchiveFiles@2
          displayName: "Step - Archive files (artifacts)"
          inputs:
            rootFolderOrFile: '$(projectRoot)'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true

        - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          displayName: 'Step - Upload package'
          artifact: drop

